# Swift 파일 포함 디렉토리 지정
included:
  - Pindora

excluded:
  - Pods
  - Carthage
  - fastlane

# 커스텀 규칙
custom_rules:

  lower_camel_case_variable:
    name: "변수는 lowerCamelCase 사용"
    regex: '\b(let|var)\s+[A-Z]'
    message: "변수 이름은 소문자로 시작하는 lowerCamelCase로 작성해주세요."
    severity: warning

  lower_camel_case_function:
    name: "함수는 lowerCamelCase 사용"
    regex: 'func\s+[A-Z]'
    message: "함수 이름은 소문자로 시작하는 lowerCamelCase로 작성해주세요."
    severity: warning

  upper_camel_case_enum:
    name: "enum은 UpperCamelCase 사용"
    regex: 'enum\s+[a-z]'
    message: "enum 이름은 대문자로 시작하는 UpperCamelCase로 작성해주세요."
    severity: warning
    
  enum_case_name:
    name: "enum case는 lowerCamelCase 사용"
    regex: '^\s*case\s+[A-Z]'
    message: "enum case는 소문자로 시작하는 lowerCamelCase로 작성해주세요."
    severity: warning

  no_force_unwrap:
    name: "강제 언래핑 금지"
    regex: '!\s*[\n;)]'
    message: "'!'는 사용하지 마세요. 옵셔널 바인딩 또는 ??를 사용해주세요."
    severity: error

  mark_format:
    name: "MARK 형식 지켜야 함"
    regex: '^\s*//\s*MARK\s*:(?!\s*-)'
    message: "// MARK: 뒤에는 반드시 `-`를 붙여주세요. 예: // MARK: - Section"
    severity: warning

#  korean_todo_comment:
#    name: "TODO/FIXME 한글로"
#    regex: '(//\s*)(TODO|FIXME)(?!:)'
#    message: "TODO 또는 FIXME 뒤에 내용을 한글로 적어주세요. 예: // TODO: 로그인 처리 필요"
#    severity: warning

#  trailing_whitespace_check:
#    name: "공백 포함 빈 줄 금지"
#    regex: '[ \t]+$'
#    message: "빈 줄에 공백(스페이스 또는 탭)이 포함되지 않도록 해주세요."
#    severity: warning



# 비활성화된 규칙(커스텀 한글 경고를 위해 swiftlint의 기본 활성화된 규칙 전부 비활성화 시킴)
disabled_rules:
  - multiple_closures_with_trailing_closure # 클로저 2개 이상일 때 후행 클로저 금지 해제
  - orphaned_doc_comment                    # 연결되지 않은 문서 주석 경고 비활성화
  - no_space_in_method_call                 # 메서드 호출 시 괄호 앞 공백 금지 비활성화
  - comment_spacing                         # 주석 뒤 공백 요구 비활성화
  - trailing_comma                          # 컬렉션 끝 쉼표 금지 비활성화
  - duplicate_imports                       # 동일한 import 구문 중복 방지
  - colon                                   # 콜론(:) 좌우 공백 스타일 규칙 비활성화
  - array_init                              # [Element]() 대신 Array<Element>() 사용 제한
  - attributes                              # 속성(Attribute)의 순서나 줄 위치 관련 경고
  - block_based_kvo                         # KVO를 block 기반으로 구현하지 않도록 제한
  - class_delegate_protocol                 # delegate 프로토콜에 class 제한자를 요구
  - closing_brace                           # 닫는 중괄호 위치 관련 스타일 규칙
  - closure_end_indentation                 # 클로저 끝의 들여쓰기 관련 스타일 규칙
  - closure_parameter_position              # 클로저 매개변수 위치 제한
  - comma                                   # 콤마 뒤 공백 또는 줄바꿈 관련 규칙
  - compiler_protocol_init                  # 컴파일러가 제공하는 프로토콜 초기화 관련
  - conditional_returns_on_newline          # return 조건문은 항상 줄바꿈할 것
  - control_statement                       # if, for 등 제어문 뒤 중괄호 요구
  - convenience_type                        # 타입을 쉽게 만드는 구조체/enum 사용 지양
  - cyclomatic_complexity                   # 복잡도 점수가 높은 함수 경고
  - discouraged_direct_init                 # 직접 생성자 호출을 지양하도록 경고
  - discouraged_optional_boolean            # Bool? 대신 다른 패턴 사용 권장
  - duplicate_enum_cases                    # 동일한 enum case 중복 선언 방지
  - empty_enum_arguments                    # 빈 열거형 인자 사용 금지
  - empty_parameters                        # 빈 괄호 매개변수 사용 지양
  - empty_parentheses_with_trailing_closure # 클로저 뒤 불필요한 괄호 제거
  - explicit_acl                            # public/private 등을 명시하지 않은 경우 경고
  - explicit_enum_raw_value                 # enum의 원시값을 명시하지 않은 경우 경고
  - explicit_init                           # 명시적 init 사용 여부
  - explicit_top_level_acl                  # 파일 상단 선언에 접근 제어자 요구
  - extension_access_modifier               # extension에 접근 제어자 명시 요구
  - fallthrough                             # fallthrough 사용에 대한 경고
  - fatal_error_message                     # fatalError에 메시지 없을 시 경고
  - file_length                             # 파일 줄 수 제한
  - file_name                               # 파일명과 타입명이 다를 경우 경고
  - first_where                             # first(where:) 대신 filter().first 사용 방지
  - force_cast                              # as! 강제 캐스팅 금지
  - force_try                               # try! 강제 시도 금지
  - force_unwrapping                        # ! 강제 언래핑 금지
  - function_body_length                    # 함수 본문 줄 수 제한
  - function_parameter_count                # 함수 매개변수 개수 제한
  - identifier_name                         # 변수/함수 이름 길이 제한
  - implicit_getter                         # getter 생략을 제한
  - implicitly_unwrapped_optional           # 암시적 언래핑 변수(!) 사용 제한
  - joined_default_parameter                # 기본 매개변수의 결합 관련 경고
  - large_tuple                             # 큰 튜플(5개 이상) 사용 지양
  - leading_whitespace                      # 줄 앞 공백 관련 규칙
  - legacy_cggeometry_functions             # CGRectMake 등 구 API 사용 제한
  - legacy_constant                         # M_PI 등 legacy 상수 사용 제한
  - legacy_constructor                      # legacy 생성자 사용 제한 (ex. NSString)
  - let_var_whitespace                      # let, var 키워드 후 공백 관련
  - line_length                             # 한 줄 길이 제한
  - mark                                    # // MARK: 주석 형식 규칙
  - missing_docs                            # 공개 API에 문서화 요구
  - modifier_order                          # 접근 제어자 및 속성 순서 규칙
  - multiline_arguments                     # 여러 줄 인자 형식 규칙
  - multiline_function_chains               # 체이닝 시 줄 바꿈 요구
  - nesting                                 # 중첩 타입이나 함수 제한
  - nimble_operator                         # Nimble 테스트 연산자 사용 제한
  - no_fallthrough_only                     # fallthrough가 유일한 코드 방지
  - notification_center_detachment          # NotificationCenter에서 해제하지 않으면 경고
  - nslocalizedstring_key                   # NSLocalizedString 키 값 경고
  - number_separator                        # 큰 숫자에 _ 사용 여부
  - object_literal                          # 이미지/색상 literal 사용 여부
  - opening_brace                           # 여는 중괄호 위치 규칙
  - operator_usage_whitespace               # 연산자 좌우 공백 관련 규칙
  - overridden_super_call                   # override 시 super 호출 누락
  - override_in_extension                   # extension에서 override 사용 제한
  - pattern_matching_keywords               # ~= 등의 패턴 매칭 연산자 스타일
  - prefixed_toplevel_constant              # 전역 상수에 prefix 요구 여부
  - private_action                          # IBAction은 private로 제한
  - private_outlet                          # IBOutlet은 private로 제한
  - private_unit_test                       # 테스트 메서드는 private 제한
  - protocol_property_accessors_order       # 프로퍼티 get/set 순서 규칙
  - quick_discouraged_call                  # Quick에서 권장하지 않는 메서드 사용
  - quick_discouraged_focused_test          # 집중 테스트(.focused) 사용 금지
  - quick_discouraged_pending_test          # 보류된 테스트(.pending) 경고
  - redundant_discardable_let               # 불필요한 _ let 제거
  - redundant_nil_coalescing                # ?? nil 같은 중복 연산 경고
  - redundant_optional_initialization       # ? = nil 같은 초기화 제거
  - redundant_string_enum_value             # enum case rawValue가 중복일 경우
  - redundant_type_annotation               # 명확한 타입에 불필요한 타입 선언
  - required_enum_case                      # 모든 case를 enum에 선언하도록 강제
  - return_arrow_whitespace                 # return → 화살표 주변 공백
  - shorthand_operator                      # += 등 축약 연산자 사용 시 스타일
  - single_test_class                       # 하나의 테스트 클래스만 있을 경우 제한
  - sorted_first_last                       # sorted { $0 < $1 } 대신 .sorted() 사용 권장
  - statement_position                      # if 등 제어문의 위치 규칙
  - strict_fileprivate                      # fileprivate 대신 private 사용 권장
  - strong_iboutlet                         # IBOutlet은 weak 사용 권장
  - superfluous_disable_command             # 불필요한 // swiftlint:disable 제거
  - switch_case_alignment                   # switch-case 들여쓰기 스타일 규칙
  - syntactic_sugar                         # Array<T> 대신 [T] 등 문법 설탕 사용 여부
  - todo                                    # TODO, FIXME 주석을 경고로 처리
  - trailing_closure                        # 후행 클로저 스타일 관련
  - trailing_newline                        # 파일 끝 줄바꿈 요구
  - trailing_semicolon                      # 세미콜론 금지
  - trailing_whitespace                     # 줄 끝 공백 제거
  - type_body_length                        # 타입 정의 줄 수 제한
  - type_name                               # 타입 이름 길이 제한
  - unneeded_break_in_switch                # 불필요한 break 경고
  - unneeded_parentheses_in_closure_argument # 클로저 인자 괄호 생략 가능 여부
  - unused_closure_parameter                # 사용하지 않는 클로저 인자 경고
  - unused_enumerated                       # enumerated 결과 미사용 시 경고
  - unused_optional_binding                 # 사용하지 않는 optional 바인딩 경고
  - valid_ibinspectable                     # IBInspectable 유효성 검사
  - vertical_parameter_alignment            # 파라미터 수직 정렬 스타일
  - vertical_whitespace                     # 코드 사이 불필요한 줄바꿈 경고
  - vertical_whitespace_between_cases       # case 사이 줄바꿈 여부
  - void_return                             # Void 반환 명시 여부
  - weak_delegate                           # delegate는 weak 선언 권장
  - xctfail_message                         # XCTFail에 메시지 요구



